name: Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Tag Name
      shell: bash
      run: |
        echo "IMAGE_TAG=$(date '+%Y%m%d%H%M')-${GITHUB_SHA:0:5}" >> "${GITHUB_ENV}"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
